// Configuration for AI Artisan Studio
const CONFIG = {
  apiEndpoint: '/api/generate',
  sampleCount: 1,
  aspectRatio: '1:1',
  productTypes: [
    { id: 'tshirt', name: 'T-Shirt', emoji: '👕', prompt_modifier: 't-shirt design' },
    { id: 'hoodie', name: 'Hoodie', emoji: '🧥', prompt_modifier: 'hoodie design' },
    { id: 'mug', name: 'Coffee Mug', emoji: '☕', prompt_modifier: 'coffee mug design' },
    { id: 'sticker', name: 'Sticker', emoji: '🏷️', prompt_modifier: 'sticker design' },
    { id: 'poster', name: 'Poster', emoji: '🖼️', prompt_modifier: 'poster design' },
    { id: 'notebook', name: 'Notebook', emoji: '📓', prompt_modifier: 'notebook design' },
    { id: 'phone-case', name: 'Phone Case', emoji: '📱', prompt_modifier: 'phone case design' },
    { id: 'tote-bag', name: 'Tote Bag', emoji: '👜', prompt_modifier: 'tote bag design' },
    { id: 'wall-art', name: 'Wall Art', emoji: '🎨', prompt_modifier: 'wall art design' },
    { id: 'business-card', name: 'Business Card', emoji: '💼', prompt_modifier: 'business card design' },
    { id: 'book-cover', name: 'Book Cover', emoji: '📚', prompt_modifier: 'book cover design' },
    { id: 'album-cover', name: 'Album Cover', emoji: '💿', prompt_modifier: 'album cover design' },
  ],
  logoStyles: [
    { id: 'minimalist', name: 'Minimalist', prompt_modifier: 'minimalist, clean, simple logo' },
    { id: 'vintage', name: 'Vintage', prompt_modifier: 'vintage, retro, aged logo' },
    { id: 'modern', name: 'Modern', prompt_modifier: 'modern, contemporary, sleek logo' },
    { id: 'retro', name: 'Retro', prompt_modifier: 'retro, 80s, nostalgic logo' },
    { id: 'geometric', name: 'Geometric', prompt_modifier: 'geometric, angular, structured logo' },
    { id: 'hand-drawn', name: 'Hand Drawn', prompt_modifier: 'hand-drawn, sketchy, organic logo' },
    { id: 'typography', name: 'Typography', prompt_modifier: 'typography-focused, text-based logo' },
    { id: 'illustration', name: 'Illustration', prompt_modifier: 'illustrated, artistic, detailed logo' },
    { id: 'abstract', name: 'Abstract', prompt_modifier: 'abstract, conceptual, artistic logo' },
    { id: 'cyberpunk', name: 'Cyberpunk', prompt_modifier: 'cyberpunk, futuristic, neon logo' },
    { id: 'organic', name: 'Organic', prompt_modifier: 'organic, flowing, natural logo' },
    { id: 'brutalist', name: 'Brutalist', prompt_modifier: 'brutalist, bold, industrial logo' },
    { id: 'art-deco', name: 'Art Deco', prompt_modifier: 'art deco, elegant, luxurious logo' },
    { id: 'psychedelic', name: 'Psychedelic', prompt_modifier: 'psychedelic, colorful, trippy logo' },
    { id: 'steampunk', name: 'Steampunk', prompt_modifier: 'steampunk, mechanical, vintage logo' },
    { id: 'watercolor', name: 'Watercolor', prompt_modifier: 'watercolor, soft, artistic logo' },
  ],
  designStyles: [
    { id: 'minimalist', name: 'Minimalist', prompt_modifier: 'minimalist, clean, simple' },
    { id: 'vintage', name: 'Vintage', prompt_modifier: 'vintage, retro, aged' },
    { id: 'modern', name: 'Modern', prompt_modifier: 'modern, contemporary, sleek' },
    { id: 'retro', name: 'Retro', prompt_modifier: 'retro, 80s, nostalgic' },
    { id: 'geometric', name: 'Geometric', prompt_modifier: 'geometric, angular, structured' },
    { id: 'hand-drawn', name: 'Hand Drawn', prompt_modifier: 'hand-drawn, sketchy, organic' },
    { id: 'typography', name: 'Typography', prompt_modifier: 'typography-focused, text-based' },
    { id: 'illustration', name: 'Illustration', prompt_modifier: 'illustrated, artistic, detailed' },
    { id: 'abstract', name: 'Abstract', prompt_modifier: 'abstract, conceptual, artistic' },
    { id: 'cyberpunk', name: 'Cyberpunk', prompt_modifier: 'cyberpunk, futuristic, neon' },
    { id: 'organic', name: 'Organic', prompt_modifier: 'organic, flowing, natural' },
    { id: 'brutalist', name: 'Brutalist', prompt_modifier: 'brutalist, bold, industrial' },
    { id: 'art-deco', name: 'Art Deco', prompt_modifier: 'art deco, elegant, luxurious' },
    { id: 'psychedelic', name: 'Psychedelic', prompt_modifier: 'psychedelic, colorful, trippy' },
    { id: 'steampunk', name: 'Steampunk', prompt_modifier: 'steampunk, mechanical, vintage' },
    { id: 'watercolor', name: 'Watercolor', prompt_modifier: 'watercolor, soft, artistic' },
    { id: 'gothic', name: 'Gothic', prompt_modifier: 'gothic, dark, mysterious' },
    { id: 'japanese', name: 'Japanese', prompt_modifier: 'japanese, zen, minimal' },
    { id: 'african', name: 'African', prompt_modifier: 'african, tribal, vibrant' },
    { id: 'celtic', name: 'Celtic', prompt_modifier: 'celtic, intricate, knotwork' },
  ],
  colorSchemes: [
    { id: 'monochrome', name: 'Monochrome', gradient: 'linear-gradient(45deg, #000000, #333333)', prompt_modifier: 'black and white, monochrome' },
    { id: 'vibrant', name: 'Vibrant', gradient: 'linear-gradient(45deg, #ff6b6b, #4ecdc4)', prompt_modifier: 'vibrant, bold colors' },
    { id: 'neutral', name: 'Neutral', gradient: 'linear-gradient(45deg, #f8f9fa, #6c757d)', prompt_modifier: 'neutral, muted colors' },
    { id: 'warm', name: 'Warm', gradient: 'linear-gradient(45deg, #ffd93d, #ff6b6b)', prompt_modifier: 'warm, earthy tones' },
    { id: 'cool', name: 'Cool', gradient: 'linear-gradient(45deg, #4ecdc4, #45b7d1)', prompt_modifier: 'cool, blue tones' },
    { id: 'pastel', name: 'Pastel', gradient: 'linear-gradient(45deg, #a8e6cf, #dcedc1)', prompt_modifier: 'pastel, soft colors' },
    { id: 'neon', name: 'Neon', gradient: 'linear-gradient(45deg, #ff00ff, #00ffff)', prompt_modifier: 'neon, bright, glowing colors' },
    { id: 'sunset', name: 'Sunset', gradient: 'linear-gradient(45deg, #ff6b35, #f7931e, #ffd23f)', prompt_modifier: 'sunset, warm, golden colors' },
    { id: 'ocean', name: 'Ocean', gradient: 'linear-gradient(45deg, #006994, #0099cc, #66ccff)', prompt_modifier: 'ocean, deep blue, aquatic colors' },
    { id: 'forest', name: 'Forest', gradient: 'linear-gradient(45deg, #2d5016, #4a7c59, #6b8e23)', prompt_modifier: 'forest, green, natural colors' },
    { id: 'desert', name: 'Desert', gradient: 'linear-gradient(45deg, #d2691e, #cd853f, #f4a460)', prompt_modifier: 'desert, sandy, earth tones' },
    { id: 'aurora', name: 'Aurora', gradient: 'linear-gradient(45deg, #00ff88, #00ffff, #0080ff)', prompt_modifier: 'aurora, northern lights, ethereal colors' },
    { id: 'cosmic', name: 'Cosmic', gradient: 'linear-gradient(45deg, #4b0082, #8a2be2, #9370db)', prompt_modifier: 'cosmic, space, purple nebula colors' },
    { id: 'fire', name: 'Fire', gradient: 'linear-gradient(45deg, #ff4500, #ff6347, #ff8c00)', prompt_modifier: 'fire, hot, burning colors' },
    { id: 'ice', name: 'Ice', gradient: 'linear-gradient(45deg, #b0e0e6, #87ceeb, #add8e6)', prompt_modifier: 'ice, cold, frozen colors' },
    { id: 'metallic', name: 'Metallic', gradient: 'linear-gradient(45deg, #c0c0c0, #a9a9a9, #808080)', prompt_modifier: 'metallic, silver, chrome colors' },
    { id: 'golden', name: 'Golden', gradient: 'linear-gradient(45deg, #ffd700, #ffb347, #ffa500)', prompt_modifier: 'golden, luxury, premium colors' },
  ],
  displayStyles: [
    { id: 'mockup', name: '3D Product Mockup', prompt_modifier: 'realistic 3D product mockup, professional photography' },
    { id: 'mockup-lifestyle', name: 'Lifestyle Mockup', prompt_modifier: 'lifestyle mockup, natural setting, professional photography' },
    { id: 'flat', name: 'Flat Design (Vector)', prompt_modifier: 'flat vector design, clean background' },
  ],
};
